/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 84f71e0e70876c1a404bf3417674cac4)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Chat";
	}
	interface Env {
		Chat: DurableObjectNamespace<import("./src/server").Chat>;
		UnpairedUsersDO: DurableObjectNamespace<import("./src/server").UnpairedUsersDO>;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
