/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 2cd5113de764660f7227809978f7da04)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "UserChat";
	}
	interface Env {
		UserChat: DurableObjectNamespace<import("./src/server").UserChat>;
		UnpairedUsersDO: DurableObjectNamespace<import("./src/server").UnpairedUsersDO>;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
